### ISSUE TITLE
What about more bash like features in the terminal?

### ISSUE THREAD

**Issue by bencarlisle15** [TheCyaniteProject/exit_code_java#3]
Features like hitting up and down to go to previous inputs. It's fairly easy to implement by creating an ArrayList of responses and using the KeyListener.

Another bash-like feature could be hitting ctr-c to stop a function. This one is a little harder to implement and would require the use of threads.

**Comment by TheCyaniteProject** [comment]
Thank you for the suggestion! These features are already planned, but will not be added for a little while. After I finish up a few things with the OS, Implement player profiles, and improve the back-end of the Terminal, then I will release an update that overhauls the Terminal. I will try to release a patch in Pre-Release 9 that will allow you to highlight text in the terminal, as this should if been implemented already.

**Comment by TheCyaniteProject** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overhaul In-Game Terminal](https://trello.com/c/F9eXNFqK/11-overhaul-in-game-terminal)

**Comment by tiagoanleite** [comment]
The use of threads is actually a very good idea to isolate each Terminal instance as in a real computer. It might be handy in the future to use timers in order to simulate processing time (like, for example, calculating hashes or simulating a download via wget). Also it was one of the reasons behind my issue with the console interpreter being a static class (see #5)
